In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('ecommerce.db')

df = pd.read_excel(r"C:\Users\PREM\OneDrive\Desktop\Internship_Project\processed\cleaned_dataset.xlsx")

df.to_sql('orders', conn, if_exists='replace', index=False)

cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('orders',)]

In [2]:
pd.read_sql_query("SELECT * FROM orders LIMIT 5", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [3]:
pd.read_sql_query("SELECT OrderID, Product, Quantity, TotalPrice FROM orders LIMIT 10", conn)

     OrderID  Product  Quantity  TotalPrice
0  ORD200000  Monitor         5     2853.10
1  ORD200001    Phone         2      302.70
2  ORD200002   Tablet         5     2753.40
3  ORD200003    Chair         1      273.19
4  ORD200004  Printer         4     2504.04
5  ORD200005    Phone         2      491.72
6  ORD200006   Laptop         1      664.42
7  ORD200007  Monitor         5      747.75
8  ORD200009     Desk         4     2037.52
9  ORD200010   Tablet         5     3129.85

In [4]:
pd.read_sql_query("SELECT * FROM orders WHERE OrderStatus = 'Delivered'", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
1,ORD200024,2024-10-30 00:00:00,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
2,ORD200025,2024-07-24 00:00:00,C42577,Monitor,1,399.98,709 Main St,Debit Card,Delivered,TRK69423327,3,WINTER15,Email,399.98
3,ORD200029,2024-09-20 00:00:00,C33260,Desk,3,423.53,930 Main St,Credit Card,Delivered,TRK59744090,6,SAVE10,Referral,1270.59
4,ORD200038,2024-12-19 00:00:00,C15924,Laptop,1,245.89,549 Main St,Debit Card,Delivered,TRK14835975,3,SAVE10,Google,245.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,ORD201166,2023-07-31 00:00:00,C95568,Chair,3,324.47,971 Main St,Cash,Delivered,TRK37075292,4,WINTER15,Email,973.41
174,ORD201168,2023-04-08 00:00:00,C89559,Laptop,2,331.42,297 Main St,Credit Card,Delivered,TRK82838108,6,WINTER15,Google,662.84
175,ORD201171,2023-08-28 00:00:00,C39911,Phone,4,518.40,699 Main St,Credit Card,Delivered,TRK80431998,7,SAVE10,Facebook,2073.60
176,ORD201187,2024-03-13 00:00:00,C26340,Desk,2,184.60,562 Main St,Gift Card,Delivered,TRK59962703,7,WINTER15,Email,369.20
177,ORD201197,2023-07-13 00:00:00,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68

In [5]:
pd.read_sql_query("SELECT * FROM orders WHERE TotalPrice > 2000", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
2,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
3,ORD200009,2023-11-21 00:00:00,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52
4,ORD200010,2023-12-29 00:00:00,C43443,Tablet,5,625.97,333 Main St,Credit Card,Returned,TRK98859248,9,WINTER15,Instagram,3129.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,ORD201146,2024-10-03 00:00:00,C36383,Monitor,5,421.44,286 Main St,Cash,Pending,TRK93336357,5,SAVE10,Instagram,2107.20
130,ORD201155,2023-08-13 00:00:00,C41478,Printer,4,534.57,667 Main St,Credit Card,Delivered,TRK62068126,6,FREESHIP,Facebook,2138.28
131,ORD201171,2023-08-28 00:00:00,C39911,Phone,4,518.40,699 Main St,Credit Card,Delivered,TRK80431998,7,SAVE10,Facebook,2073.60
132,ORD201179,2023-01-08 00:00:00,C84630,Laptop,5,518.55,907 Main St,Credit Card,Cancelled,TRK48054997,6,WINTER15,Instagram,2592.75
133,ORD201199,2023-06-11 00:00:00,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [6]:
pd.read_sql_query("SELECT * FROM orders WHERE Product LIKE 'L%'", conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200006,2025-06-17 00:00:00,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
1,ORD200013,2023-08-30 00:00:00,C88348,Laptop,3,201.49,903 Main St,Credit Card,Returned,TRK81913874,4,FREESHIP,Facebook,604.47
2,ORD200024,2024-10-30 00:00:00,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
3,ORD200037,2024-10-14 00:00:00,C10054,Laptop,2,76.74,409 Main St,Cash,Returned,TRK94005261,7,SAVE10,Instagram,153.48
4,ORD200038,2024-12-19 00:00:00,C15924,Laptop,1,245.89,549 Main St,Debit Card,Delivered,TRK14835975,3,SAVE10,Google,245.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,ORD201119,2024-11-24 00:00:00,C99024,Laptop,1,684.65,250 Main St,Credit Card,Delivered,TRK24675988,1,FREESHIP,Email,684.65
123,ORD201130,2025-02-16 00:00:00,C24347,Laptop,2,323.45,533 Main St,Credit Card,Returned,TRK27233265,5,FREESHIP,Instagram,646.90
124,ORD201163,2024-06-11 00:00:00,C30643,Laptop,3,306.29,966 Main St,Credit Card,Returned,TRK19477485,7,WINTER15,Instagram,918.87
125,ORD201168,2023-04-08 00:00:00,C89559,Laptop,2,331.42,297 Main St,Credit Card,Delivered,TRK82838108,6,WINTER15,Google,662.84
126,ORD201179,2023-01-08 00:00:00,C84630,Laptop,5,518.55,907 Main St,Credit Card,Cancelled,TRK48054997,6,WINTER15,Instagram,2592.75

In [7]:
pd.read_sql_query("SELECT OrderID, Product, TotalPrice FROM orders ORDER BY TotalPrice DESC LIMIT 10", conn)

     OrderID  Product  TotalPrice
0  ORD200789   Tablet     3456.40
1  ORD200632   Laptop     3390.80
2  ORD200328   Tablet     3370.20
3  ORD200107  Printer     3353.75
4  ORD200326   Laptop     3352.40
5  ORD201065  Printer     3334.00
6  ORD201031    Phone     3322.55
7  ORD200463   Laptop     3313.90
8  ORD200361  Printer     3299.25
9  ORD200367   Laptop     3293.85

In [8]:
pd.read_sql_query("""
SELECT Product, COUNT(*) AS OrderCount
FROM orders
GROUP BY Product
ORDER BY OrderCount DESC
""", conn)

   Product  OrderCount
0  Printer         137
1   Tablet         132
2    Chair         130
3     Desk         129
4   Laptop         127
5    Phone         116
6  Monitor         115

In [9]:
pd.read_sql_query("""
SELECT Product, SUM(TotalPrice) AS TotalRevenue
FROM orders
GROUP BY Product
ORDER BY TotalRevenue DESC
""", conn)

   Product  TotalRevenue
0  Printer     151151.33
1   Tablet     141926.11
2   Laptop     140869.64
3    Chair     136974.18
4  Monitor     130493.97
5     Desk     119237.76
6    Phone     118161.30

In [10]:
pd.read_sql_query("""
SELECT PaymentMethod, AVG(TotalPrice) AS AvgOrderValue
FROM orders
GROUP BY PaymentMethod
ORDER BY AvgOrderValue DESC
""", conn)

  PaymentMethod  AvgOrderValue
0   Credit Card    1165.879218
1     Gift Card    1058.904111
2          Cash    1049.247527
3        Online    1011.642809
4    Debit Card    1008.884431

In [11]:
pd.read_sql_query("""
SELECT OrderStatus,
       COUNT(*) AS TotalOrders,
       SUM(TotalPrice) AS Revenue,
       AVG(TotalPrice) AS AvgValue
FROM orders
GROUP BY OrderStatus
ORDER BY Revenue DESC
""", conn)

  OrderStatus  TotalOrders    Revenue     AvgValue
0   Cancelled          191  214771.90  1124.460209
1   Delivered          178  188804.28  1060.698202
2     Pending          175  187165.99  1069.519943
3     Shipped          171  180785.73  1057.226491
4    Returned          171  167286.39   978.282982

In [12]:
pd.read_sql_query("""
SELECT ReferralSource, COUNT(*) AS Orders
FROM orders
WHERE OrderStatus = 'Delivered'
GROUP BY ReferralSource
ORDER BY Orders DESC
""", conn)

  ReferralSource  Orders
0          Email      50
1      Instagram      39
2       Facebook      34
3         Google      30
4       Referral      25